# Import numpy, pandas and Json library

In [1]:
import numpy as np
import pandas as pd
import json

# Import/Read Covid-19 data which are json file .

In [2]:
df1=pd.read_json('/content/drive/MyDrive/Covid-19 Project/data.min.json')
df2 = pd.read_json('/content/drive/MyDrive/Covid-19 Project/timeseries.min.json')

In [3]:
df1

,AN,AP,AR,AS,BR,CH,CT,DL,DN,GA,...,PY,RJ,SK,TG,TN,TR,TT,UP,UT,WB
delta,"{'tested': 1376, 'vaccinated1': 3, 'vaccinated...","{'confirmed': 385, 'deceased': 4, 'recovered':...","{'confirmed': 1, 'recovered': 9, 'tested': 334...","{'confirmed': 212, 'deceased': 1, 'recovered':...","{'confirmed': 8, 'recovered': 9, 'tested': 226...","{'confirmed': 5, 'recovered': 3, 'tested': 140...","{'confirmed': 32, 'deceased': 1, 'recovered': ...","{'confirmed': 45, 'recovered': 46, 'tested': 5...","{'recovered': 1, 'vaccinated1': 3, 'vaccinated...","{'confirmed': 23, 'recovered': 53, 'tested': 2...",...,"{'confirmed': 38, 'recovered': 45, 'tested': 2...","{'confirmed': 2, 'recovered': 2, 'tested': 134...","{'confirmed': 21, 'deceased': 1, 'recovered': ...","{'confirmed': 121, 'deceased': 1, 'recovered':...","{'confirmed': 1009, 'deceased': 19, 'recovered...","{'confirmed': 12, 'recovered': 2, 'tested': 35...","{'confirmed': 12907, 'deceased': 251, 'other':...","{'confirmed': 6, 'recovered': 6, 'tested': 161...","{'confirmed': 5, 'recovered': 9, 'tested': 952...","{'confirmed': 914, 'deceased': 15, 'recovered'..."
delta21_14,{'confirmed': 9},{'confirmed': 3220},{'confirmed': 87},{'confirmed': 1499},{'confirmed': 30},{'confirmed': 23},{'confirmed': 124},{'confirmed': 195},{'confirmed': 4},{'confirmed': 409},...,{'confirmed': 343},{'confirmed': 31},{'confirmed': 82},{'confirmed': 1068},{'confirmed': 8827},{'confirmed': 49},{'confirmed': 109755},{'confirmed': 74},{'confirmed': 88},{'confirmed': 4193}
delta7,"{'confirmed': 3, 'recovered': 5, 'tested': 893...","{'confirmed': 2873, 'deceased': 30, 'recovered...","{'confirmed': 66, 'recovered': 97, 'tested': 4...","{'confirmed': 2056, 'deceased': 24, 'recovered...","{'confirmed': 40, 'recovered': 31, 'tested': 1...","{'confirmed': 28, 'recovered': 20, 'tested': 1...","{'confirmed': 205, 'deceased': 5, 'recovered':...","{'confirmed': 267, 'recovered': 239, 'tested':...","{'recovered': 2, 'vaccinated1': 2802, 'vaccina...","{'confirmed': 222, 'deceased': 6, 'recovered':...",...,"{'confirmed': 278, 'recovered': 315, 'tested':...","{'confirmed': 27, 'recovered': 26, 'tested': 9...","{'confirmed': 79, 'deceased': 2, 'other': 6, '...","{'confirmed': 1189, 'deceased': 9, 'recovered'...","{'confirmed': 7407, 'deceased': 97, 'recovered...","{'confirmed': 87, 'recovered': 62, 'tested': 2...","{'confirmed': 96071, 'deceased': 3727, 'other'...","{'confirmed': 63, 'deceased': 1, 'recovered': ...","{'confirmed': 75, 'deceased': 1, 'other': 12, ...","{'confirmed': 6453, 'deceased': 86, 'recovered..."
districts,"{'Nicobars': {'delta7': {'vaccinated1': 62, 'v...","{'Anantapur': {'delta': {'confirmed': 4, 'reco...","{'Anjaw': {'delta7': {'vaccinated1': 45, 'vacc...","{'Baksa': {'delta': {'vaccinated1': 39, 'vacci...","{'Araria': {'delta': {'vaccinated1': 5177, 'va...","{'Chandigarh': {'delta': {'confirmed': 5, 'rec...","{'Balod': {'delta': {'vaccinated1': 523, 'vacc...","{'Delhi': {'delta': {'confirmed': 45, 'recover...",{'Dadra and Nagar Haveli': {'delta': {'vaccina...,"{'North Goa': {'delta': {'vaccinated1': 1070, ...",...,"{'Karaikal': {'delta': {'confirmed': 6, 'recov...","{'Ajmer': {'delta': {'vaccinated1': 110, 'vacc...",{'East Sikkim': {'delta7': {'vaccinated1': 528...,"{'Adilabad': {'delta': {'vaccinated1': 165, 'v...",{'Airport Quarantine': {'delta21_14': {'confir...,"{'Dhalai': {'delta': {'vaccinated1': 5, 'vacci...",NaN,"{'Agra': {'delta': {'vaccinated1': 178, 'vacci...","{'Almora': {'delta': {'vaccinated1': 37, 'vacc...","{'Alipurduar': {'delta': {'confirmed': 4, 'rec..."
meta,"{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...",...,"{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1...","{'date': '2021-10-31', 'last_updated': '2021-1..."
total,"{'confirmed': 7651, 'deceased': 129, 'recovere...","{'confirmed': 2066450, 'deceased': 14373, 'rec...","{'confirmed': 55155, 'deceased': 280, 'recover...","{'confirmed': 610645, 'deceased': 5997, 'other...","{'confirmed': 726098, 'deceased': 9661, 'other...","{'confirmed': 65351, 'deceased': 820, 'recover...","{'confirmed': 1006052, 'deceased': 13577, 'rec...","{'confirmed': 1439870, 'deceased': 25091, 'rec...","{'confirmed': 10681, 'deceased': 4, 'other': 3...","{'confirmed': 178108, 'deceased': 3364, 'recov...",...,"{'confirmed': 128013, 'deceased': 1857, 'recov...","{'confirmed': 954429, 'deceased': 8954, 'recov...","{'confirmed': 31979, 'deceased': 396, 'other':...","{'confirmed': 671463, 'deceased': 3956, 'recov...","{'confirmed': 2702623, 'deceased': 36116, 'rec...","{'confirmed': 84468, 'deceased': 813, 'other':...","{'confirmed': 34285612, 'deceased': 458470, 'o...","{'confirmed': 1710158, 'deceased': 22900, 'rec...","{'confirmed': 343896, 'deceased': 7400, 'other...","{'confirmed': 1592908, 'deceased': 19141, 'rec..."

In [4]:
df2

,AN,AP,AR,AS,BR,CH,CT,DL,DN,GA,...,RJ,SK,TG,TN,TR,TT,UN,UP,UT,WB
dates,"{'2020-03-26': {'delta': {'confirmed': 1}, 'de...","{'2020-03-12': {'delta': {'confirmed': 1}, 'de...","{'2020-04-02': {'delta': {'confirmed': 1}, 'de...","{'2020-03-31': {'delta': {'confirmed': 1}, 'de...","{'2020-03-22': {'delta': {'confirmed': 2}, 'de...","{'2020-03-19': {'delta': {'confirmed': 1}, 'de...","{'2020-03-19': {'delta': {'confirmed': 1}, 'de...","{'2020-03-02': {'delta': {'confirmed': 1}, 'de...","{'2020-04-09': {'delta': {'tested': 80}, 'delt...","{'2020-03-25': {'delta': {'confirmed': 3}, 'de...",...,"{'2020-03-03': {'delta': {'confirmed': 1}, 'de...","{'2020-05-04': {'delta': {'tested': 170}, 'del...","{'2020-03-02': {'delta': {'confirmed': 1}, 'de...","{'2020-03-07': {'delta': {'confirmed': 1}, 'de...","{'2020-04-06': {'delta': {'confirmed': 1}, 'de...","{'2020-01-30': {'delta': {'confirmed': 1}, 'de...","{'2020-05-19': {'delta': {'confirmed': 814}, '...","{'2020-03-04': {'delta': {'confirmed': 7}, 'de...","{'2020-03-15': {'delta': {'confirmed': 1}, 'de...","{'2020-03-17': {'delta': {'confirmed': 1}, 'de..."

In [5]:
df2.iloc[0,0]

{'2020-03-26': {'delta': {'confirmed': 1},
  'delta7': {'confirmed': 1},
  'total': {'confirmed': 1}},
 '2020-03-27': {'delta': {'confirmed': 5},
  'delta7': {'confirmed': 6},
  'total': {'confirmed': 6}},
 '2020-03-28': {'delta': {'confirmed': 3},
  'delta7': {'confirmed': 9},
  'total': {'confirmed': 9}},
 '2020-03-29': {'delta7': {'confirmed': 9}, 'total': {'confirmed': 9}},
 '2020-03-30': {'delta': {'confirmed': 1},
  'delta7': {'confirmed': 10},
  'total': {'confirmed': 10}},
 '2020-03-31': {'delta7': {'confirmed': 10}, 'total': {'confirmed': 10}},
 '2020-04-01': {'delta7': {'confirmed': 10}, 'total': {'confirmed': 10}},
 '2020-04-02': {'delta7': {'confirmed': 9}, 'total': {'confirmed': 10}},
 '2020-04-03': {'delta7': {'confirmed': 4}, 'total': {'confirmed': 10}},
 '2020-04-04': {'delta7': {'confirmed': 1}, 'total': {'confirmed': 10}},
 '2020-04-05': {'delta7': {'confirmed': 1}, 'total': {'confirmed': 10}},
 '2020-04-06': {'total': {'confirmed': 10}},
 '2020-04-07': {'total': {'confirmed': 10}},
 '2020-04-08': {'delta': {'confirmed': 1},
  'delta7': {'confirmed': 1},
  'total': {'confirmed': 11}},
 '2020-04-09': {'delta': {'recovered': 10},
  'delta7': {'confirmed': 1, 'recovered': 10},
  'total': {'confirmed': 11, 'recovered': 10}},
 '2020-04-10': {'delta7': {'confirmed': 1, 'recovered': 10},
  'total': {'confirmed': 11, 'recovered': 10}},
 '2020-04-11': {'delta7': {'confirmed': 1, 'recovered': 10},
  'total': {'confirmed': 11, 'recovered': 10}},
 '2020-04-12': {'delta7': {'confirmed': 1, 'recovered': 10},
  'total': {'confirmed': 11, 'recovered': 10}},
 '2020-04-13': {'delta7': {'confirmed': 1, 'recovered': 10},
  'total': {'confirmed': 11, 'recovered': 10}},
 '2020-04-14': {'delta7': {'confirmed': 1, 'recovered': 10},
  'total': {'confirmed': 11, 'recovered': 10}},
 '2020-04-15': {'delta7': {'recovered': 10},
  'total': {'confirmed': 11, 'recovered': 10}},
 '2020-04-16': {'delta': {'recovered': 1},
  'delta7': {'recovered': 1},
  'total': {'confirmed': 11, 'recovered': 11}},
 '2020-04-17': {'delta': {'confirmed': 1, 'tested': 1403},
  'delta7': {'confirmed': 1, 'recovered': 1, 'tested': 1403},
  'total': {'confirmed': 12, 'recovered': 11, 'tested': 1403}},
 '2020-04-18': {'delta': {'confirmed': 2},
  'delta7': {'confirmed': 3, 'recovered': 1, 'tested': 1403},
  'total': {'confirmed': 14, 'recovered': 11, 'tested': 1403}},
 '2020-04-19': {'delta': {'confirmed': 1},
  'delta7': {'confirmed': 4, 'recovered': 1, 'tested': 1403},
  'total': {'confirmed': 15, 'recovered': 11, 'tested': 1403}},
 '2020-04-20': {'delta': {'confirmed': 1},
  'delta7': {'confirmed': 5, 'recovered': 1, 'tested': 1403},
  'total': {'confirmed': 16, 'recovered': 11, 'tested': 1403}},
 '2020-04-21': {'delta': {'confirmed': 1},
  'delta7': {'confirmed': 6, 'recovered': 1, 'tested': 1403},
  'total': {'confirmed': 17, 'recovered': 11, 'tested': 1403}},
 '2020-04-22': {'delta': {'confirmed': 1},
  'delta7': {'confirmed': 7, 'recovered': 1, 'tested': 1403},
  'total': {'confirmed': 18, 'recovered': 11, 'tested': 1403}},
 '2020-04-23': {'delta': {'confirmed': 4},
  'delta7': {'confirmed': 11, 'tested': 1403},
  'total': {'confirmed': 22, 'recovered': 11, 'tested': 1403}},
 '2020-04-24': {'delta': {'confirmed': 7, 'tested': 1276},
  'delta7': {'confirmed': 17, 'tested': 1276},
  'total': {'confirmed': 29, 'recovered': 11, 'tested': 2679}},
 '2020-04-25': {'delta': {'confirmed': 4},
  'delta7': {'confirmed': 19, 'tested': 1276},
  'total': {'confirmed': 33, 'recovered': 11, 'tested': 2679}},
 '2020-04-26': {'delta7': {'confirmed': 18, 'tested': 1276},
  'total': {'confirmed': 33, 'recovered': 11, 'tested': 2679}},
 '2020-04-27': {'delta': {'tested': 169},
  'delta7': {'confirmed': 17, 'tested': 1445},
  'total': {'confirmed': 33, 'recovered': 11, 'tested': 2848}},
 '2020-04-28': {'delta': {'recovered': 4},
  'delta7': {'confirmed': 16, 'recovered': 4, 'tested': 1445},
  'total': {'confirmed': 33, 'recovered': 15, 'tested': 2848}},
 '2020-04-29': {'delta7': {'confirmed': 15, 'recovered': 4, 'tested': 1445},
  'total': {'confirmed': 33, 'recovered': 15, 'tested': 2848}},
 '2020-04-30': {'delta': {'recovered': 1},
  'delta7': {'confirmed': 11, 'recovered': 5, 'tested': 1445},
  'total': {'confirmed': 33, 'recovered': 16, 'tested': 2848}},
 '2020-05-01': {'delta': {'tested': 906},
  'delta7': {'confirmed': 4, 'recovered': 5, 'tested': 1075},
  'total': {'confirmed': 33, 'recovered': 16, 'tested': 3754}},
 '2020-05-02': {'delta': {'recovered': 10},
  'delta7': {'recovered': 15, 'tested': 1075},
  'total': {'confirmed': 33, 'recovered': 26, 'tested': 3754}},
 '2020-05-03': {'delta': {'recovered': 6},
  'delta7': {'recovered': 21, 'tested': 1075},
  'total': {'confirmed': 33, 'recovered': 32, 'tested': 3754}},
 '2020-05-04': {'delta7': {'recovered': 21, 'tested': 906},
  'total': {'confirmed': 33, 'recovered': 32, 'tested': 3754}},
 '2020-05-05': {'delta7': {'recovered': 17, 'tested': 906},
  'total': {'confirmed': 33, 'recovered': 32, 'tested': 3754}},
 '2020-05-06': {'delta7': {'recovered': 17, 'tested': 906},
  'total': {'confirmed': 33, 'recovered': 32, 'tested': 3754}},
 '2020-05-07': {'delta': {'recovered': 1},
  'delta7': {'recovered': 17, 'tested': 906},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 3754}},
 '2020-05-08': {'delta7': {'recovered': 17},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 3754}},
 '2020-05-09': {'delta7': {'recovered': 7},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 3754}},
 '2020-05-10': {'delta7': {'recovered': 1},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 3754}},
 '2020-05-11': {'delta7': {'recovered': 1},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 3754}},
 '2020-05-12': {'delta7': {'recovered': 1},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 3754}},
 '2020-05-13': {'delta7': {'recovered': 1},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 3754}},
 '2020-05-14': {'total': {'confirmed': 33, 'recovered': 33, 'tested': 3754}},
 '2020-05-15': {'total': {'confirmed': 33, 'recovered': 33, 'tested': 3754}},
 '2020-05-16': {'delta': {'tested': 2923},
  'delta7': {'tested': 2923},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 6677}},
 '2020-05-17': {'delta7': {'tested': 2923},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 6677}},
 '2020-05-18': {'delta7': {'tested': 2923},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 6677}},
 '2020-05-19': {'delta': {'tested': 288},
  'delta7': {'tested': 3211},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 6965}},
 '2020-05-20': {'delta': {'tested': 117},
  'delta7': {'tested': 3328},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7082}},
 '2020-05-21': {'delta': {'tested': 85},
  'delta7': {'tested': 3413},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7167}},
 '2020-05-22': {'delta': {'tested': 96},
  'delta7': {'tested': 3509},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7263}},
 '2020-05-23': {'delta': {'tested': 64},
  'delta7': {'tested': 650},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7327}},
 '2020-05-24': {'delta7': {'tested': 650},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7327}},
 '2020-05-25': {'delta': {'tested': 36},
  'delta7': {'tested': 686},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7363}},
 '2020-05-26': {'delta': {'tested': 85},
  'delta7': {'tested': 483},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7448}},
 '2020-05-27': {'delta': {'tested': 51},
  'delta7': {'tested': 417},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7499}},
 '2020-05-28': {'delta': {'tested': 20},
  'delta7': {'tested': 352},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7519}},
 '2020-05-29': {'delta': {'tested': 48},
  'delta7': {'tested': 304},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7567}},
 '2020-05-30': {'delta7': {'tested': 240},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7567}},
 '2020-05-31': {'delta': {'tested': 139},
  'delta7': {'tested': 379},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7706}},
 '2020-06-01': {'delta': {'tested': 99},
  'delta7': {'tested': 442},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 7805}},
 '2020-06-02': {'delta': {'tested': 281},
  'delta7': {'tested': 638},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 8086}},
 '2020-06-03': {'delta': {'tested': 209},
  'delta7': {'tested': 796},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 8295}},
 '2020-06-04': {'delta': {'tested': 118},
  'delta7': {'tested': 894},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 8413}},
 '2020-06-05': {'delta': {'tested': 281},
  'delta7': {'tested': 1127},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 8694}},
 '2020-06-06': {'delta': {'tested': 343},
  'delta7': {'tested': 1470},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 9037}},
 '2020-06-07': {'delta': {'tested': 205},
  'delta7': {'tested': 1536},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 9242}},
 '2020-06-08': {'delta': {'tested': 99},
  'delta7': {'tested': 1536},
  'total': {'confirmed': 33, 'recovered': 33, 'tested': 9341}},
 '2020-06-09': {'delta': {'confirmed': 1, 'tested': 518},
  'delta7': {'confirmed': 1, 'tested': 1773},
  'total': {'confirmed': 34, 'recovered': 33, 'tested': 9859}},
 '2020-06-10': {'delta': {'confirmed': 1, 'tested': 151},
  'delta7': {'confirmed': 2, 'tested': 1715},
  'total': {'confirmed': 35, 'recovered': 33, 'tested': 10010}},
 '2020-06-11': {'delta': {'confirmed': 3, 'tested': 216},
  'delta7': {'confirmed': 5, 'tested': 1813},
  'total': {'confirmed': 38, 'recovered': 33, 'tested': 10226}},
 '2020-06-12': {'delta': {'tested': 471},
  'delta7': {'confirmed': 5, 'tested': 2003},
  'total': {'confirmed': 38, 'recovered': 33, 'tested': 10697}},
 '2020-06-13': {'delta': {'tested': 258},
  'delta7': {'confirmed': 5, 'tested': 1918},
  'total': {'confirmed': 38, 'recovered': 33, 'tested': 10955}},
 '2020-06-14': {'delta': {'confirmed': 2, 'tested': 401},
  'delta7': {'confirmed': 7, 'tested': 2114},
  'total': {'confirmed': 40, 'recovered': 33, 'tested': 11356}},
 '2020-06-15': {'delta': {'confirmed': 1, 'tested': 162},
  'delta7': {'confirmed': 8, 'tested': 2177},
  'total': {'confirmed': 41, 'recovered': 33, 'tested': 11518}},
 '2020-06-16': {'delta': {'confirmed': 3, 'tested': 291},
  'delta7': {'confirmed': 10, 'tested': 1950},
  'total': {'confirmed': 44, 'recovered': 33, 'tested': 11809}},
 '2020-06-17': {'delta': {'tested': 430},
  'delta7': {'confirmed': 9, 'tested': 2229},
  'total': {'confirmed': 44, 'recovered': 33, 'tested': 12239}},
 '2020-06-18': {'delta': {'confirmed': 1, 'recovered': 2, 'tested': 383},
  'delta7': {'confirmed': 7, 'recovered': 2, 'tested': 2396},
  'total': {'confirmed': 45, 'recovered': 35, 'tested': 12622}},
 '2020-06-19': {'delta': {'confirmed': 2, 'tested': 308},
  'delta7': {'confirmed': 9, 'recovered': 2, 'tested': 2233},
  'total': {'confirmed': 47, 'recovered': 35, 'tested': 12930}},
 '2020-06-20': {'delta': {'tested': 390},
  'delta7': {'confirmed': 9, 'recovered': 2, 'tested': 2365},
  'total': {'confirmed': 47, 'recovered': 35, 'tested': 13320}},
 '2020-06-21': {'delta': {'confirmed': 1, 'recovered': 2, 'tested': 114},
  'delta7': {'confirmed': 8, 'recovered': 4, 'tested': 2078},
  'total': {'confirmed': 48, 'recovered': 37, 'tested': 13434}},
 '2020-06-22': {'delta': {'tested': 77},
  'delta7': {'confirmed': 7, 'recovered': 4, 'tested': 1993},
  'total': {'confirmed': 48, 'recovered': 37, 'tested': 13511}},
 '2020-06-23': {'delta': {'confirmed': 2, 'recovered': 3, 'tested': 212},
  'delta7': {'confirmed': 6, 'recovered': 7, 'tested': 1914},
  'total': {'confirmed': 50, 'recovered': 40, 'tested': 13723}},
 '2020-06-24': {'delta': {'confirmed': 6, 'recovered': 1, 'tested': 271},
  'delta7': {'confirmed': 12, 'recovered': 8, 'tested': 1755},
  'total': {'confirmed': 56, 'recovered': 41, 'tested': 13994}},
 '2020-06-25': {'delta': {'confirmed': 2, 'tested': 283},
  'delta7': {'confirmed': 13, 'recovered': 6, 'tested': 1655},
  'total': {'confirmed': 58, 'recovered': 41, 'tested': 14277}},
 '2020-06-26': {'delta': {'confirmed': 14, 'recovered': 2, 'tested': 306},
  'delta7': {'confirmed': 25, 'recovered': 8, 'tested': 1653},
  'total': {'confirmed': 72, 'recovered': 43, 'tested': 14583}},
 '2020-06-27': {'delta': {'tested': 268},
  'delta7': {'confirmed': 25, 'recovered': 8, 'tested': 1531},
  'total': {'confirmed': 72, 'recovered': 43, 'tested': 14851}},
 '2020-06-28': {'delta': {'confirmed': 11, 'recovered': 2, 'tested': 243},
  'delta7': {'confirmed': 35, 'recovered': 8, 'tested': 1660},
  'total': {'confirmed': 83, 'recovered': 45, 'tested': 15094}},
 '2020-06-29': {'delta': {'confirmed': 7, 'tested': 316},
  'delta7': {'confirmed': 42, 'recovered': 8, 'tested': 1899},
  'total': {'confirmed': 90, 'recovered': 45, 'tested': 15410}},
 '2020-06-30': {'delta': {'confirmed': 7, 'tested': 299},
  'delta7': {'confirmed': 47, 'recovered': 5, 'tested': 1986},
  'total': {'confirmed': 97, 'recovered': 45, 'tested': 15709}},
 '2020-07-01': {'delta': {'confirmed': 3, 'recovered': 5, 'tested': 273},
  'delta7': {'confirmed': 44, 'recovered': 9, 'tested': 1988},
  'total': {'confirmed': 100, 'recovered': 50, 'tested': 15982}},
 '2020-07-02': {'delta': {'confirmed': 9, 'recovered': 1, 'tested': 296},
  'delta7': {'confirmed': 51, 'recovered': 10, 'tested': 2001},
  'total': {'confirmed': 109, 'recovered': 51, 'tested': 16278}},
 '2020-07-03': {'delta': {'confirmed': 7, 'recovered': 3, 'tested': 348},
  'delta7': {'confirmed': 44, 'recovered': 11, 'tested': 2043},
  'total': {'confirmed': 116, 'recovered': 54, 'tested': 16626}},
 '2020-07-04': {'delta': {'confirmed': 3, 'recovered': 12, 'tested': 206},
  'delta7': {'confirmed': 47, 'recovered': 23, 'tested': 1981},
  'total': {'confirmed': 119, 'recovered': 66, 'tested': 16832}},
 '2020-07-05': {'delta': {'confirmed': 6, 'recovered': 6, 'tested': 77},
  'delta7': {'confirmed': 42, 'recovered': 27, 'tested': 1815},
  'total': {'confirmed': 125, 'recovered': 72, 'tested': 16909}},
 '2020-07-06': {'delta': {'confirmed': 16, 'recovered': 2, 'tested': 186},
  'delta7': {'confirmed': 51, 'recovered': 29, 'tested': 1685},
  'total': {'confirmed': 141, 'recovered': 74, 'tested': 17095}},
 '2020-07-07': {'delta': {'confirmed': 6, 'tested': 286},
  'delta7': {'confirmed': 50, 'recovered': 29, 'tested': 1672},
  'total': {'confirmed': 147, 'recovered': 74, 'tested': 17381}},
 '2020-07-08': {'delta': {'confirmed': 2, 'tested': 262},
  'delta7': {'confirmed': 49, 'recovered': 24, 'tested': 1661},
  'total': {'confirmed': 149, 'recovered': 74, 'tested': 17643}},
 '2020-07-09': {'delta': {'confirmed': 7, 'recovered': 9, 'tested': 209},
  'delta7': {'confirmed': 47, 'recovered': 32, 'tested': 1574},
  'total': {'confirmed': 156, 'recovered': 83, 'tested': 17852}},
 '2020-07-10': {'delta': {'recovered': 9, 'tested': 194},
  'delta7': {'confirmed': 40, 'recovered': 38, 'tested': 1420},
  'total': {'confirmed': 156, 'recovered': 92, 'tested': 18046}},
 '2020-07-11': {'delta': {'tested': 269},
  'delta7': {'confirmed': 37, 'recovered': 26, 'tested': 1483},
  'total': {'confirmed': 156, 'recovered': 92, 'tested': 18315}},
 '2020-07-12': {'delta': {'confirmed': 7, 'recovered': 8, 'tested': 132},
  'delta7': {'confirmed': 38, 'recovered': 28, 'tested': 1538},
  'total': {'confirmed': 163, 'recovered': 100, 'tested': 18447}},
 '2020-07-13': {'delta': {'confirmed': 3, 'recovered': 9, 'tested': 162},
  'delta7': {'confirmed': 25, 'recovered': 35, 'tested': 1514},
  'total': {'confirmed': 166, 'recovered': 109, 'tested': 18609}},
 '2020-07-14': {'delta': {'confirmed': 5, 'recovered': 20, 'tested': 275},
  'delta7': {'confirmed': 24, 'recovered': 55, 'tested': 1503},
  'total': {'confirmed': 171, 'recovered': 129, 'tested': 18884}},
 '2020-07-15': {'delta': {'confirmed': 5, 'recovered': 1, 'tested': 177},
  'delta7': {'confirmed': 27, 'recovered': 56, 'tested': 1418},
  'total': {'confirmed': 176, 'recovered': 130, 'tested': 19061}},
 '2020-07-16': {'delta': {'confirmed': 4, 'recovered': 3, 'tested': 166},
  'delta7': {'confirmed': 24, 'recovered': 50, 'tested': 1375},
  'total': {'confirmed': 180, 'recovered': 133, 'tested': 19227}},
 '2020-07-17': {'delta': {'confirmed': 4, 'recovered': 9, 'tested': 194},
  'delta7': {'confirmed': 28, 'recovered': 50, 'tested': 1375},
  'total': {'confirmed': 184, 'recovered': 142, 'tested': 19421}},
 '2020-07-18': {'delta': {'confirmed': 4, 'recovered': 3, 'tested': 250},
  'delta7': {'confirmed': 32, 'recovered': 53, 'tested': 1356},
  'total': {'confirmed': 188, 'recovered': 145, 'tested': 19671}},
 '2020-07-19': {'delta': {'confirmed': 15, 'other': 1, 'tested': 233},
  'delta7': {'confirmed': 40, 'other': 1, 'recovered': 45, 'tested': 1457},
  'total': {'confirmed': 203, 'other': 1, 'recovered': 145, 'tested': 19904}},
 '2020-07-20': {'delta': {'confirmed': 4, 'recovered': 6, 'tested': 397},
  'delta7': {'confirmed': 41, 'other': 1, 'recovered': 42, 'tested': 1692},
  'total': {'confirmed': 207, 'other': 1, 'recovered': 151, 'tested': 20301}},
 '2020-07-21': {'delta': {'confirmed': 5, 'recovered': 8, 'tested': 341},
  'delta7': {'confirmed': 41, 'other': 1, 'recovered': 30, 'tested': 1758},
  'total': {'confirmed': 212, 'other': 1, 'recovered': 159, 'tested': 20642}},
 '2020-07-22': {'delta': {'confirmed': 9, 'recovered': 4, 'tested': 401},
  'delta7': {'confirmed': 45, 'other': 1, 'recovered': 33, 'tested': 1982},
  'total': {'confirmed': 221, 'other': 1, 'recovered': 163, 'tested': 21043}},
 '2020-07-23': {'delta': {'confirmed': 19, 'recovered': 7, 'tested': 267},
  'delta7': {'confirmed': 60, 'other': 1, 'recovered': 37, 'tested': 2083},
  'total': {'confirmed': 240, 'other': 1, 'recovered': 170, 'tested': 21310}},
 '2020-07-24': {'delta': {'confirmed': 19, 'recovered': 4, 'tested': 433},
  'delta7': {'confirmed': 75, 'other': 1, 'recovered': 32, 'tested': 2322},
  'total': {'confirmed': 259, 'other': 1, 'recovered': 174, 'tested': 21743}},
 '2020-07-25': {'delta': {'confirmed': 31, 'recovered': 2, 'tested': 222},
  'delta7': {'confirmed': 102, 'other': 1, 'recovered': 31, 'tested': 2294},
  'total': {'confirmed': 290, 'other': 1, 'recovered': 176, 'tested': 21965}},
 '2020-07-26': {'delta': {'confirmed': 28, 'recovered': 4, 'tested': 84},
  'delta7': {'confirmed': 115, 'recovered': 35, 'tested': 2145},
  'total': {'confirmed': 318, 'other': 1, 'recovered': 180, 'tested': 22049}},
 '2020-07-27': {'delta': {'confirmed': 20,
   'deceased': 1,
   'recovered': 12,
   'tested': 499},
  'delta7': {'confirmed': 131, 'deceased': 1, 'recovered': 41, 'tested': 2247},
  'total': {'confirmed': 338,
   'deceased': 1,
   'other': 1,
   'recovered': 192,
   'tested': 22548}},
 '2020-07-28': {'delta': {'confirmed': 25, 'recovered': 4, 'tested': 377},
  'delta7': {'confirmed': 151, 'deceased': 1, 'recovered': 37, 'tested': 2283},
  'total': {'confirmed': 363,
   'deceased': 1,
   'other': 1,
   'recovered': 196,
   'tested': 22925}},
 '2020-07-29': {'delta': {'confirmed': 65,
   'deceased': 1,
   'recovered': 5,
   'tested': 292},
  'delta7': {'confirmed': 207, 'deceased': 2, 'recovered': 38, 'tested': 2174},
  'total': {'confirmed': 428,
   'deceased': 2,
   'other': 1,
   'recovered': 201,
   'tested': 23217}},
 '2020-07-30': {'delta': {'confirmed': 42, 'deceased': 1, 'tested': 398},
  'delta7': {'confirmed': 230, 'deceased': 3, 'recovered': 31, 'tested': 2305},
  'total': {'confirmed': 470,
   'deceased': 3,
   'other': 1,
   'recovered': 201,
   'tested': 23615}},
 '2020-07-31': {'delta': {'confirmed': 78,
   'deceased': 2,
   'recovered': 13,
   'tested': 423},
  'delta7': {'confirmed': 289, 'deceased': 5, 'recovered': 40, 'tested': 2295},
  'total': {'confirmed': 548,
   'deceased': 5,
   'other': 1,
   'recovered': 214,
   'tested': 24038}},
 '2020-08-01': {'delta': {'confirmed': 88,

In [6]:
df2.columns

Index(['AN', 'AP', 'AR', 'AS', 'BR', 'CH', 'CT', 'DL', 'DN', 'GA', 'GJ', 'HP',
       'HR', 'JH', 'JK', 'KA', 'KL', 'LA', 'LD', 'MH', 'ML', 'MN', 'MP', 'MZ',
       'NL', 'OR', 'PB', 'PY', 'RJ', 'SK', 'TG', 'TN', 'TR', 'TT', 'UN', 'UP',
       'UT', 'WB'],
      dtype='object')

#Creat DataFrame of timeseries data.

In [7]:
time_series1 =pd.json_normalize(df2.iloc[0,:])

In [8]:
time_series1.shape

(38, 10481)

In [9]:
time_series1 = time_series1.T
time_series1

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
2020-03-26.delta.confirmed,1.0,1.0,NaN,NaN,3.0,NaN,3.0,4.0,NaN,NaN,...,5.0,NaN,4.0,3.0,NaN,73.0,NaN,4.0,NaN,1.0
2020-03-26.delta7.confirmed,1.0,8.0,NaN,NaN,7.0,6.0,5.0,25.0,NaN,3.0,...,34.0,NaN,29.0,26.0,NaN,532.0,NaN,22.0,2.0,9.0
2020-03-26.total.confirmed,1.0,11.0,NaN,NaN,7.0,7.0,6.0,39.0,NaN,3.0,...,43.0,NaN,45.0,29.0,NaN,730.0,NaN,42.0,5.0,10.0
2020-03-27.delta.confirmed,5.0,2.0,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,...,7.0,NaN,14.0,9.0,NaN,153.0,NaN,7.0,NaN,5.0
2020-03-27.delta7.confirmed,6.0,10.0,NaN,NaN,9.0,3.0,5.0,20.0,NaN,3.0,...,33.0,NaN,40.0,35.0,NaN,627.0,NaN,25.0,2.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-27.delta.vaccinated2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2313.0,NaN,NaN,NaN,NaN
2021-02-28.delta.other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN
2021-08-28.delta.vaccinated1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5152003.0,NaN,NaN,NaN,NaN
2021-08-28.delta.vaccinated2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2776790.0,NaN,NaN,NaN,NaN
2021-10-24.delta.other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN

In [10]:
# Download test_series1
# from google.colab import files
# time_series1.to_csv('time_series1.csv') 
# files.download('time_series1.csv')

# Create Various DataFrame such as delta,delta21_14, delta14,meta,total etc.

Using json normalize.

In [11]:
delta =pd.json_normalize(df1.iloc[0,:])
delta

      tested  vaccinated1  vaccinated2  confirmed  deceased  recovered  other
0     1376.0          3.0         13.0        NaN       NaN        NaN    NaN
1    39848.0      20497.0      24137.0      385.0       4.0      675.0    NaN
2      334.0         42.0        195.0        1.0       NaN        9.0    NaN
3    15060.0      19124.0      37463.0      212.0       1.0      236.0    NaN
4   226443.0     114694.0     145827.0        8.0       NaN        9.0    NaN
5     1403.0        211.0       1282.0        5.0       NaN        3.0    NaN
6    11869.0      21312.0      39393.0       32.0       1.0       32.0    NaN
7    56751.0      12482.0      11839.0       45.0       NaN       46.0    NaN
8        NaN          3.0         20.0        NaN       NaN        1.0    NaN
9     2361.0       2572.0      12404.0       23.0       NaN       53.0    NaN
10   34282.0      14685.0      62096.0       20.0       NaN       23.0    NaN
11    3613.0        371.0       8192.0       85.0       1.0      198.0    NaN
12   20588.0       7867.0      15801.0       11.0       NaN       10.0    NaN
13   31238.0      41034.0      51488.0       10.0       NaN        8.0    NaN
14   38915.0       1584.0      45202.0       95.0       NaN       79.0    NaN
15  106939.0      17604.0      28163.0      292.0      11.0      345.0    NaN
16   65158.0       2010.0      11914.0     7167.0     167.0     6439.0    NaN
17     388.0          NaN          2.0       11.0       NaN        9.0    NaN
18      31.0          NaN          4.0        NaN       NaN        NaN    NaN
19  108040.0      53161.0      31988.0     1172.0      20.0     1399.0    NaN
20    1559.0         38.0        203.0       22.0       1.0       51.0    NaN
21    1689.0        705.0       4283.0       63.0       1.0       62.0    NaN
22   55368.0       5713.0      77062.0       16.0       NaN        8.0    NaN
23    5945.0         10.0         51.0      579.0       2.0      610.0    NaN
24     468.0        193.0        822.0       11.0       1.0       21.0    1.0
25   69675.0      21420.0      25651.0      488.0       4.0      450.0    NaN
26   34152.0       3321.0       4418.0       26.0       1.0       25.0    NaN
27    2662.0        171.0        532.0       38.0       NaN       45.0    NaN
28   13454.0       9399.0      29672.0        2.0       NaN        2.0    NaN
29     389.0          NaN          NaN       21.0       1.0        8.0    NaN
30   25021.0      38781.0      26738.0      121.0       1.0      183.0    NaN
31  123701.0      77325.0     106584.0     1009.0      19.0     1183.0    NaN
32    3501.0          3.0        650.0       12.0       NaN        2.0    NaN
33  881379.0     750410.0     933460.0    12907.0     251.0    13152.0    1.0
34  161458.0      53401.0      57556.0        6.0       NaN        6.0    NaN
35    9524.0       1065.0      12934.0        5.0       NaN        9.0    NaN
36   47417.0     209609.0      58881.0      914.0      15.0      913.0    NaN

In [12]:
# add state_code column to delta dataframe.
state_name = df1.columns
state_name = list(state_name)
delta.insert(loc = 0,column ='state_code',value = state_name)
delta

,state_code,tested,vaccinated1,vaccinated2,confirmed,deceased,recovered,other
0,AN,1376.0,3.0,13.0,NaN,NaN,NaN,NaN
1,AP,39848.0,20497.0,24137.0,385.0,4.0,675.0,NaN
2,AR,334.0,42.0,195.0,1.0,NaN,9.0,NaN
3,AS,15060.0,19124.0,37463.0,212.0,1.0,236.0,NaN
4,BR,226443.0,114694.0,145827.0,8.0,NaN,9.0,NaN
5,CH,1403.0,211.0,1282.0,5.0,NaN,3.0,NaN
6,CT,11869.0,21312.0,39393.0,32.0,1.0,32.0,NaN
7,DL,56751.0,12482.0,11839.0,45.0,NaN,46.0,NaN
8,DN,NaN,3.0,20.0,NaN,NaN,1.0,NaN
9,GA,2361.0,2572.0,12404.0,23.0,NaN,53.0,NaN
10,GJ,34282.0,14685.0,62096.0,20.0,NaN,23.0,NaN
11,HP,3613.0,371.0,8192.0,85.0,1.0,198.0,NaN
12,HR,20588.0,7867.0,15801.0,11.0,NaN,10.0,NaN
13,JH,31238.0,41034.0,51488.0,10.0,NaN,8.0,NaN
14,JK,38915.0,1584.0,45202.0,95.0,NaN,79.0,NaN
15,KA,106939.0,17604.0,28163.0,292.0,11.0,345.0,NaN
16,KL,65158.0,2010.0,11914.0,7167.0,167.0,6439.0,NaN
17,LA,388.0,NaN,2.0,11.0,NaN,9.0,NaN
18,LD,31.0,NaN,4.0,NaN,NaN,NaN,NaN
19,MH,108040.0,53161.0,31988.0,1172.0,20.0,1399.0,NaN
20,ML,1559.0,38.0,203.0,22.0,1.0,51.0,NaN
21,MN,1689.0,705.0,4283.0,63.0,1.0,62.0,NaN
22,MP,55368.0,5713.0,77062.0,16.0,NaN,8.0,NaN
23,MZ,5945.0,10.0,51.0,579.0,2.0,610.0,NaN
24,NL,468.0,193.0,822.0,11.0,1.0,21.0,1.0
25,OR,69675.0,21420.0,25651.0,488.0,4.0,450.0,NaN
26,PB,34152.0,3321.0,4418.0,26.0,1.0,25.0,NaN
27,PY,2662.0,171.0,532.0,38.0,NaN,45.0,NaN
28,RJ,13454.0,9399.0,29672.0,2.0,NaN,2.0,NaN
29,SK,389.0,NaN,NaN,21.0,1.0,8.0,NaN
30,TG,25021.0,38781.0,26738.0,121.0,1.0,183.0,NaN
31,TN,123701.0,77325.0,106584.0,1009.0,19.0,1183.0,NaN
32,TR,3501.0,3.0,650.0,12.0,NaN,2.0,NaN
33,TT,881379.0,750410.0,933460.0,12907.0,251.0,13152.0,1.0
34,UP,161458.0,53401.0,57556.0,6.0,NaN,6.0,NaN
35,UT,9524.0,1065.0,12934.0,5.0,NaN,9.0,NaN
36,WB,47417.0,209609.0,58881.0,914.0,15.0,913.0,NaN

crate dataframe Using loop

In [16]:
List =[]
for i in range(37):
  List.append(df1.iloc[0,i])

In [17]:
DF =pd.DataFrame()
for i in range(37):
  a = pd.DataFrame.from_dict(List[i],orient = 'index')
  f=[DF,a]
  DF = pd.concat(f,axis=1)

In [19]:
DF =DF.T
DF

     tested  vaccinated1  vaccinated2  confirmed  deceased  recovered  other
0    1376.0          3.0         13.0        NaN       NaN        NaN    NaN
0   39848.0      20497.0      24137.0      385.0       4.0      675.0    NaN
0     334.0         42.0        195.0        1.0       NaN        9.0    NaN
0   15060.0      19124.0      37463.0      212.0       1.0      236.0    NaN
0  226443.0     114694.0     145827.0        8.0       NaN        9.0    NaN
0    1403.0        211.0       1282.0        5.0       NaN        3.0    NaN
0   11869.0      21312.0      39393.0       32.0       1.0       32.0    NaN
0   56751.0      12482.0      11839.0       45.0       NaN       46.0    NaN
0       NaN          3.0         20.0        NaN       NaN        1.0    NaN
0    2361.0       2572.0      12404.0       23.0       NaN       53.0    NaN
0   34282.0      14685.0      62096.0       20.0       NaN       23.0    NaN
0    3613.0        371.0       8192.0       85.0       1.0      198.0    NaN
0   20588.0       7867.0      15801.0       11.0       NaN       10.0    NaN
0   31238.0      41034.0      51488.0       10.0       NaN        8.0    NaN
0   38915.0       1584.0      45202.0       95.0       NaN       79.0    NaN
0  106939.0      17604.0      28163.0      292.0      11.0      345.0    NaN
0   65158.0       2010.0      11914.0     7167.0     167.0     6439.0    NaN
0     388.0          NaN          2.0       11.0       NaN        9.0    NaN
0      31.0          NaN          4.0        NaN       NaN        NaN    NaN
0  108040.0      53161.0      31988.0     1172.0      20.0     1399.0    NaN
0    1559.0         38.0        203.0       22.0       1.0       51.0    NaN
0    1689.0        705.0       4283.0       63.0       1.0       62.0    NaN
0   55368.0       5713.0      77062.0       16.0       NaN        8.0    NaN
0    5945.0         10.0         51.0      579.0       2.0      610.0    NaN
0     468.0        193.0        822.0       11.0       1.0       21.0    1.0
0   69675.0      21420.0      25651.0      488.0       4.0      450.0    NaN
0   34152.0       3321.0       4418.0       26.0       1.0       25.0    NaN
0    2662.0        171.0        532.0       38.0       NaN       45.0    NaN
0   13454.0       9399.0      29672.0        2.0       NaN        2.0    NaN
0     389.0          NaN          NaN       21.0       1.0        8.0    NaN
0   25021.0      38781.0      26738.0      121.0       1.0      183.0    NaN
0  123701.0      77325.0     106584.0     1009.0      19.0     1183.0    NaN
0    3501.0          3.0        650.0       12.0       NaN        2.0    NaN
0  881379.0     750410.0     933460.0    12907.0     251.0    13152.0    1.0
0  161458.0      53401.0      57556.0        6.0       NaN        6.0    NaN
0    9524.0       1065.0      12934.0        5.0       NaN        9.0    NaN
0   47417.0     209609.0      58881.0      914.0      15.0      913.0    NaN

In [21]:
state_index = df1.columns
state_index = list(state_index)

In [22]:
DF.index = state_index

In [23]:
DF = DF.reset_index()
DF

,index,tested,vaccinated1,vaccinated2,confirmed,deceased,recovered,other
0,AN,1376.0,3.0,13.0,NaN,NaN,NaN,NaN
1,AP,39848.0,20497.0,24137.0,385.0,4.0,675.0,NaN
2,AR,334.0,42.0,195.0,1.0,NaN,9.0,NaN
3,AS,15060.0,19124.0,37463.0,212.0,1.0,236.0,NaN
4,BR,226443.0,114694.0,145827.0,8.0,NaN,9.0,NaN
5,CH,1403.0,211.0,1282.0,5.0,NaN,3.0,NaN
6,CT,11869.0,21312.0,39393.0,32.0,1.0,32.0,NaN
7,DL,56751.0,12482.0,11839.0,45.0,NaN,46.0,NaN
8,DN,NaN,3.0,20.0,NaN,NaN,1.0,NaN
9,GA,2361.0,2572.0,12404.0,23.0,NaN,53.0,NaN
10,GJ,34282.0,14685.0,62096.0,20.0,NaN,23.0,NaN
11,HP,3613.0,371.0,8192.0,85.0,1.0,198.0,NaN
12,HR,20588.0,7867.0,15801.0,11.0,NaN,10.0,NaN
13,JH,31238.0,41034.0,51488.0,10.0,NaN,8.0,NaN
14,JK,38915.0,1584.0,45202.0,95.0,NaN,79.0,NaN
15,KA,106939.0,17604.0,28163.0,292.0,11.0,345.0,NaN
16,KL,65158.0,2010.0,11914.0,7167.0,167.0,6439.0,NaN
17,LA,388.0,NaN,2.0,11.0,NaN,9.0,NaN
18,LD,31.0,NaN,4.0,NaN,NaN,NaN,NaN
19,MH,108040.0,53161.0,31988.0,1172.0,20.0,1399.0,NaN
20,ML,1559.0,38.0,203.0,22.0,1.0,51.0,NaN
21,MN,1689.0,705.0,4283.0,63.0,1.0,62.0,NaN
22,MP,55368.0,5713.0,77062.0,16.0,NaN,8.0,NaN
23,MZ,5945.0,10.0,51.0,579.0,2.0,610.0,NaN
24,NL,468.0,193.0,822.0,11.0,1.0,21.0,1.0
25,OR,69675.0,21420.0,25651.0,488.0,4.0,450.0,NaN
26,PB,34152.0,3321.0,4418.0,26.0,1.0,25.0,NaN
27,PY,2662.0,171.0,532.0,38.0,NaN,45.0,NaN
28,RJ,13454.0,9399.0,29672.0,2.0,NaN,2.0,NaN
29,SK,389.0,NaN,NaN,21.0,1.0,8.0,NaN
30,TG,25021.0,38781.0,26738.0,121.0,1.0,183.0,NaN
31,TN,123701.0,77325.0,106584.0,1009.0,19.0,1183.0,NaN
32,TR,3501.0,3.0,650.0,12.0,NaN,2.0,NaN
33,TT,881379.0,750410.0,933460.0,12907.0,251.0,13152.0,1.0
34,UP,161458.0,53401.0,57556.0,6.0,NaN,6.0,NaN
35,UT,9524.0,1065.0,12934.0,5.0,NaN,9.0,NaN
36,WB,47417.0,209609.0,58881.0,914.0,15.0,913.0,NaN

In [24]:
DF.rename(columns = {'index':'State'},inplace=True)

In [ ]:
# delta = DF
# delta
# Similarly we can create Dataframe for delta7,total.

# Similarly for others.

In [25]:
delta21_14	= pd.json_normalize(df1.iloc[1,:])
delta21_14.insert(loc = 0,column ='state_code',value = state_name)
delta21_14

   state_code  confirmed
0          AN        9.0
1          AP     3220.0
2          AR       87.0
3          AS     1499.0
4          BR       30.0
5          CH       23.0
6          CT      124.0
7          DL      195.0
8          DN        4.0
9          GA      409.0
10         GJ      149.0
11         HP      958.0
12         HR       83.0
13         JH       78.0
14         JK      529.0
15         KA     2432.0
16         KL    59521.0
17         LA       26.0
18         LD        NaN
19         MH    13825.0
20         ML      530.0
21         MN      734.0
22         MP       63.0
23         MZ     6770.0
24         NL      162.0
25         OR     3381.0
26         PB      159.0
27         PY      343.0
28         RJ       31.0
29         SK       82.0
30         TG     1068.0
31         TN     8827.0
32         TR       49.0
33         TT   109755.0
34         UP       74.0
35         UT       88.0
36         WB     4193.0

In [42]:
delta7	= pd.json_normalize(df1.iloc[2,:])
delta7.insert(loc = 0,column ='state_code',value = state_name)
delta7

,state_code,confirmed,recovered,tested,vaccinated1,vaccinated2,deceased,other
0,AN,3.0,5.0,8936.0,884,10640,NaN,NaN
1,AP,2873.0,3590.0,254532.0,1223010,1887005,30.0,NaN
2,AR,66.0,97.0,4788.0,3312,23647,NaN,NaN
3,AS,2056.0,2215.0,269097.0,274869,849889,24.0,NaN
4,BR,40.0,31.0,1378539.0,1286708,2144970,NaN,NaN
5,CH,28.0,20.0,10726.0,3680,21641,NaN,NaN
6,CT,205.0,103.0,147451.0,379374,604260,5.0,NaN
7,DL,267.0,239.0,395086.0,160323,269146,NaN,NaN
8,DN,NaN,2.0,NaN,2802,14244,NaN,NaN
9,GA,222.0,409.0,19026.0,8418,46494,6.0,NaN
10,GJ,159.0,116.0,328489.0,335172,1660382,2.0,NaN
11,HP,1537.0,1154.0,64352.0,13244,234011,20.0,-1.0
12,HR,95.0,87.0,148110.0,160777,368141,NaN,NaN
13,JH,137.0,250.0,464579.0,299587,428313,3.0,NaN
14,JK,611.0,572.0,254608.0,33383,414843,3.0,NaN
15,KA,2347.0,2339.0,724215.0,623591,1373861,75.0,NaN
16,KL,53326.0,48406.0,506604.0,109805,792534,3089.0,NaN
17,LA,58.0,28.0,2475.0,525,1532,NaN,NaN
18,LD,NaN,NaN,1625.0,69,796,NaN,NaN
19,MH,8117.0,15146.0,773516.0,1611778,1282938,200.0,7.0
20,ML,256.0,460.0,13944.0,7871,41927,4.0,NaN
21,MN,439.0,652.0,12787.0,7665,71276,10.0,NaN
22,MP,105.0,74.0,393209.0,148817,2034460,1.0,NaN
23,MZ,4098.0,5685.0,42841.0,4302,11262,21.0,NaN
24,NL,130.0,144.0,4606.0,4706,23628,6.0,13.0
25,OR,3046.0,3230.0,473919.0,731837,917236,24.0,NaN
26,PB,192.0,162.0,221114.0,200182,223256,8.0,NaN
27,PY,278.0,315.0,21095.0,8324,20073,NaN,NaN
28,RJ,27.0,26.0,95132.0,271500,864947,NaN,NaN
29,SK,79.0,76.0,2847.0,782,14044,2.0,6.0
30,TG,1189.0,1121.0,261086.0,1072389,961422,9.0,NaN
31,TN,7407.0,8852.0,858304.0,788134,1578082,97.0,NaN
32,TR,87.0,62.0,22126.0,4155,74642,NaN,NaN
33,TT,96071.0,101753.0,8431577.0,15883780,24527530,3727.0,37.0
34,UP,63.0,58.0,1140736.0,2266921,3130828,1.0,NaN
35,UT,75.0,74.0,83377.0,25250,258381,1.0,12.0
36,WB,6453.0,5953.0,300114.0,3809597,1871612,86.0,NaN

In [43]:
meta	= pd.json_normalize(df1.iloc[4,:])
meta.insert(loc = 0,column ='state_code',value = state_name)
meta = meta.iloc[:,:-5]
meta
# meta.drop(['column_name'],axis=1,inplace=True)

   state_code        date               last_updated  population
0          AN  2021-10-31  2021-11-01T11:03:10+05:30      397000
1          AP  2021-10-31  2021-11-01T09:54:14+05:30    52221000
2          AR  2021-10-31  2021-11-01T11:20:24+05:30     1504000
3          AS  2021-10-31  2021-11-01T09:54:14+05:30    34293000
4          BR  2021-10-31  2021-11-01T09:54:14+05:30   119520000
5          CH  2021-10-31  2021-11-01T09:54:14+05:30     1179000
6          CT  2021-10-31  2021-11-01T09:54:14+05:30    28724000
7          DL  2021-10-31  2021-11-01T09:54:14+05:30    19814000
8          DN  2021-10-31  2021-11-01T09:54:14+05:30      959000
9          GA  2021-10-31  2021-11-01T09:54:14+05:30     1540000
10         GJ  2021-10-31  2021-11-01T09:54:14+05:30    67936000
11         HP  2021-10-31  2021-11-01T09:54:14+05:30     7300000
12         HR  2021-10-31  2021-11-01T09:54:14+05:30    28672000
13         JH  2021-10-31  2021-11-01T09:54:14+05:30    37403000
14         JK  2021-10-31  2021-11-01T09:54:14+05:30    13203000
15         KA  2021-10-31  2021-11-01T09:54:14+05:30    65798000
16         KL  2021-10-31  2021-11-01T09:54:14+05:30    35125000
17         LA  2021-10-31  2021-11-01T09:54:14+05:30      293000
18         LD  2021-10-31  2021-11-01T11:03:10+05:30       68000
19         MH  2021-10-31  2021-11-01T09:54:14+05:30   122153000
20         ML  2021-10-31  2021-11-01T09:54:14+05:30     3224000
21         MN  2021-10-31  2021-11-01T09:54:14+05:30     3103000
22         MP  2021-10-31  2021-11-01T09:54:14+05:30    82232000
23         MZ  2021-10-31  2021-11-01T09:54:14+05:30     1192000
24         NL  2021-10-31  2021-11-01T09:54:14+05:30     2150000
25         OR  2021-10-31  2021-11-01T09:54:14+05:30    43671000
26         PB  2021-10-31  2021-11-01T09:54:14+05:30    29859000
27         PY  2021-10-31  2021-11-01T09:54:14+05:30     1504000
28         RJ  2021-10-31  2021-11-01T09:54:14+05:30    77264000
29         SK  2021-10-31  2021-10-31T20:49:45+05:30      664000
30         TG  2021-10-31  2021-11-01T09:54:14+05:30    37220000
31         TN  2021-10-31  2021-11-01T09:54:14+05:30    75695000
32         TR  2021-10-31  2021-11-01T09:54:14+05:30     3992000
33         TT  2021-10-31  2021-11-01T11:20:24+05:30  1332900000
34         UP  2021-10-31  2021-11-01T09:54:14+05:30   224979000
35         UT  2021-10-31  2021-11-01T09:54:14+05:30    11141000
36         WB  2021-10-31  2021-11-01T09:54:14+05:30    96906000

In [44]:
total	= pd.json_normalize(df1.iloc[5,:])
total.insert(loc = 0,column ='state_code',value = state_name)
total

,state_code,confirmed,deceased,recovered,tested,vaccinated1,vaccinated2,other
0,AN,7651,129,7518,598033,294001,200157,NaN
1,AP,2066450,14373,2047722,29518787,32976969,20375181,NaN
2,AR,55155,280,54774,1185436,771875,534486,NaN
3,AS,610645,5997,600974,24712042,20172463,8068795,1347.0
4,BR,726098,9661,716390,50531824,49874828,18346781,1.0
5,CH,65351,820,64495,792851,926035,546981,NaN
6,CT,1006052,13577,992159,13709510,14851682,7343273,NaN
7,DL,1439870,25091,1414431,29427753,13055636,7425404,NaN
8,DN,10681,4,10644,72410,660753,370255,31.0
9,GA,178108,3364,174392,1468399,1262568,911114,NaN
10,GJ,826577,10089,816283,30928063,44735217,25972387,NaN
11,HP,224106,3738,218410,3685011,5713695,3443823,16.0
12,HR,771252,10049,761068,13032504,17772376,8115463,NaN
13,JH,348764,5138,343518,15985878,14986646,5585648,NaN
14,JK,332249,4432,326915,16202346,9511073,5149471,NaN
15,KA,2988333,38082,2941578,50873103,42497761,22858384,29.0
16,KL,4968657,31681,4857181,37886378,25306499,13658343,529.0
17,LA,20962,208,20687,555568,208798,152280,NaN
18,LD,10365,51,10270,263541,55129,45951,44.0
19,MH,6611078,140216,6450585,62667211,67198794,30975692,3619.0
20,ML,83627,1450,81746,1151665,1103275,641819,NaN
21,MN,123731,1921,121102,1367673,1249436,719413,NaN
22,MP,792854,10524,782215,20294225,49911938,20838045,NaN
23,MZ,121359,432,114612,1298444,711597,512029,NaN
24,NL,31842,685,29904,395416,709553,490663,1043.0
25,OR,1041457,8386,1029147,21994343,25736641,11560912,NaN
26,PB,602401,16559,585591,15429415,15942714,6238973,NaN
27,PY,128013,1857,125726,1919060,733922,404355,NaN
28,RJ,954429,8954,945443,14807752,42544909,20097635,NaN
29,SK,31979,396,31063,261343,521763,451509,325.0
30,TG,671463,3956,663498,27569831,22498559,9772398,NaN
31,TN,2702623,36116,2655015,51159242,41279432,17619141,NaN
32,TR,84468,813,83466,1983127,2508477,1621329,63.0
33,TT,34285612,458470,33661339,609201294,732371508,330752697,13197.0
34,UP,1710158,22900,1687151,83635222,98178865,32681895,NaN
35,UT,343896,7400,330195,7781148,7478017,3898342,6150.0
36,WB,1592908,19141,1565471,19228303,56192166,21559747,NaN

Download files

In [ ]:
# from google.colab import files
# delta.to_csv('delta.csv') 
# files.download('delta.csv')
# delta21_14.to_csv('delta21_14.csv') 
# files.download('delta21_14.csv')
# delta7.to_csv('delta7.csv') 
# files.download('delta7.csv')
# meta.to_csv('meta.csv') 
# files.download('meta.csv')
# total.to_csv('total.csv') 
# files.download('total.csv')

# Making parent table by merging delta,delta21_14,delta7,meta and total.

Rename column name.

In [45]:
delta.rename(columns = {'tested':'tested_delta','vaccinated1':'vaccinated1_delta','vaccinated2':'vaccinated2_delta','confirmed':'confirmed_delta','deceased':'deceased_delta','recovered':'recovered_delta','other':'other_delta'},inplace=True)

In [46]:
delta21_14.rename(columns = {'confirmed':'confirmed_delta21_14'},inplace=True)

In [47]:
delta7.rename(columns = {'tested':'tested_delta7','vaccinated1':'vaccinated1_delta7','vaccinated2':'vaccinated2_delta7','confirmed':'confirmed_delta7','deceased':'deceased_delta7','recovered':'recovered_delta7','other':'other_delta7'},inplace=True)

In [48]:
meta.rename(columns = {'date':'date_meta','last_updated':'last_updated_meta','population':'population_meta','tested.date':'tested.date_meta','tested.source':'tested.source_meta','vaccinated.date':'vaccinated.date_meta','notes':'notes_meta'},inplace=True)

In [49]:
total.rename(columns = {'tested':'tested_total','vaccinated1':'vaccinated1_total','vaccinated2':'vaccinated2_total','confirmed':'confirmed_total','deceased':'deceased_total','recovered':'recovered_total','other':'other_total'},inplace=True)

Merge table on state_code column as it is common for all .

In [50]:
parent_table = pd.merge(pd.merge(pd.merge(pd.merge(delta,delta21_14,on = 'state_code',how='outer'),delta7,on = 'state_code',how='outer'),meta,on = 'state_code',how='outer'),total,on = 'state_code',how='outer')

In [51]:
parent_table

,state_code,tested_delta,vaccinated1_delta,vaccinated2_delta,confirmed_delta,deceased_delta,recovered_delta,other_delta,confirmed_delta21_14,confirmed_delta7,...,date_meta,last_updated_meta,population_meta,confirmed_total,deceased_total,recovered_total,tested_total,vaccinated1_total,vaccinated2_total,other_total
0,AN,1376.0,3.0,13.0,NaN,NaN,NaN,NaN,9.0,3.0,...,2021-10-31,2021-11-01T11:03:10+05:30,397000,7651,129,7518,598033,294001,200157,NaN
1,AP,39848.0,20497.0,24137.0,385.0,4.0,675.0,NaN,3220.0,2873.0,...,2021-10-31,2021-11-01T09:54:14+05:30,52221000,2066450,14373,2047722,29518787,32976969,20375181,NaN
2,AR,334.0,42.0,195.0,1.0,NaN,9.0,NaN,87.0,66.0,...,2021-10-31,2021-11-01T11:20:24+05:30,1504000,55155,280,54774,1185436,771875,534486,NaN
3,AS,15060.0,19124.0,37463.0,212.0,1.0,236.0,NaN,1499.0,2056.0,...,2021-10-31,2021-11-01T09:54:14+05:30,34293000,610645,5997,600974,24712042,20172463,8068795,1347.0
4,BR,226443.0,114694.0,145827.0,8.0,NaN,9.0,NaN,30.0,40.0,...,2021-10-31,2021-11-01T09:54:14+05:30,119520000,726098,9661,716390,50531824,49874828,18346781,1.0
5,CH,1403.0,211.0,1282.0,5.0,NaN,3.0,NaN,23.0,28.0,...,2021-10-31,2021-11-01T09:54:14+05:30,1179000,65351,820,64495,792851,926035,546981,NaN
6,CT,11869.0,21312.0,39393.0,32.0,1.0,32.0,NaN,124.0,205.0,...,2021-10-31,2021-11-01T09:54:14+05:30,28724000,1006052,13577,992159,13709510,14851682,7343273,NaN
7,DL,56751.0,12482.0,11839.0,45.0,NaN,46.0,NaN,195.0,267.0,...,2021-10-31,2021-11-01T09:54:14+05:30,19814000,1439870,25091,1414431,29427753,13055636,7425404,NaN
8,DN,NaN,3.0,20.0,NaN,NaN,1.0,NaN,4.0,NaN,...,2021-10-31,2021-11-01T09:54:14+05:30,959000,10681,4,10644,72410,660753,370255,31.0
9,GA,2361.0,2572.0,12404.0,23.0,NaN,53.0,NaN,409.0,222.0,...,2021-10-31,2021-11-01T09:54:14+05:30,1540000,178108,3364,174392,1468399,1262568,911114,NaN
10,GJ,34282.0,14685.0,62096.0,20.0,NaN,23.0,NaN,149.0,159.0,...,2021-10-31,2021-11-01T09:54:14+05:30,67936000,826577,10089,816283,30928063,44735217,25972387,NaN
11,HP,3613.0,371.0,8192.0,85.0,1.0,198.0,NaN,958.0,1537.0,...,2021-10-31,2021-11-01T09:54:14+05:30,7300000,224106,3738,218410,3685011,5713695,3443823,16.0
12,HR,20588.0,7867.0,15801.0,11.0,NaN,10.0,NaN,83.0,95.0,...,2021-10-31,2021-11-01T09:54:14+05:30,28672000,771252,10049,761068,13032504,17772376,8115463,NaN
13,JH,31238.0,41034.0,51488.0,10.0,NaN,8.0,NaN,78.0,137.0,...,2021-10-31,2021-11-01T09:54:14+05:30,37403000,348764,5138,343518,15985878,14986646,5585648,NaN
14,JK,38915.0,1584.0,45202.0,95.0,NaN,79.0,NaN,529.0,611.0,...,2021-10-31,2021-11-01T09:54:14+05:30,13203000,332249,4432,326915,16202346,9511073,5149471,NaN
15,KA,106939.0,17604.0,28163.0,292.0,11.0,345.0,NaN,2432.0,2347.0,...,2021-10-31,2021-11-01T09:54:14+05:30,65798000,2988333,38082,2941578,50873103,42497761,22858384,29.0
16,KL,65158.0,2010.0,11914.0,7167.0,167.0,6439.0,NaN,59521.0,53326.0,...,2021-10-31,2021-11-01T09:54:14+05:30,35125000,4968657,31681,4857181,37886378,25306499,13658343,529.0
17,LA,388.0,NaN,2.0,11.0,NaN,9.0,NaN,26.0,58.0,...,2021-10-31,2021-11-01T09:54:14+05:30,293000,20962,208,20687,555568,208798,152280,NaN
18,LD,31.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-10-31,2021-11-01T11:03:10+05:30,68000,10365,51,10270,263541,55129,45951,44.0
19,MH,108040.0,53161.0,31988.0,1172.0,20.0,1399.0,NaN,13825.0,8117.0,...,2021-10-31,2021-11-01T09:54:14+05:30,122153000,6611078,140216,6450585,62667211,67198794,30975692,3619.0
20,ML,1559.0,38.0,203.0,22.0,1.0,51.0,NaN,530.0,256.0,...,2021-10-31,2021-11-01T09:54:14+05:30,3224000,83627,1450,81746,1151665,1103275,641819,NaN
21,MN,1689.0,705.0,4283.0,63.0,1.0,62.0,NaN,734.0,439.0,...,2021-10-31,2021-11-01T09:54:14+05:30,3103000,123731,1921,121102,1367673,1249436,719413,NaN
22,MP,55368.0,5713.0,77062.0,16.0,NaN,8.0,NaN,63.0,105.0,...,2021-10-31,2021-11-01T09:54:14+05:30,82232000,792854,10524,782215,20294225,49911938,20838045,NaN
23,MZ,5945.0,10.0,51.0,579.0,2.0,610.0,NaN,6770.0,4098.0,...,2021-10-31,2021-11-01T09:54:14+05:30,1192000,121359,432,114612,1298444,711597,512029,NaN
24,NL,468.0,193.0,822.0,11.0,1.0,21.0,1.0,162.0,130.0,...,2021-10-31,2021-11-01T09:54:14+05:30,2150000,31842,685,29904,395416,709553,490663,1043.0
25,OR,69675.0,21420.0,25651.0,488.0,4.0,450.0,NaN,3381.0,3046.0,...,2021-10-31,2021-11-01T09:54:14+05:30,43671000,1041457,8386,1029147,21994343,25736641,11560912,NaN
26,PB,34152.0,3321.0,4418.0,26.0,1.0,25.0,NaN,159.0,192.0,...,2021-10-31,2021-11-01T09:54:14+05:30,29859000,602401,16559,585591,15429415,15942714,6238973,NaN
27,PY,2662.0,171.0,532.0,38.0,NaN,45.0,NaN,343.0,278.0,...,2021-10-31,2021-11-01T09:54:14+05:30,1504000,128013,1857,125726,1919060,733922,404355,NaN
28,RJ,13454.0,9399.0,29672.0,2.0,NaN,2.0,NaN,31.0,27.0,...,2021-10-31,2021-11-01T09:54:14+05:30,77264000,954429,8954,945443,14807752,42544909,20097635,NaN
29,SK,389.0,NaN,NaN,21.0,1.0,8.0,NaN,82.0,79.0,...,2021-10-31,2021-10-31T20:49:45+05:30,664000,31979,396,31063,261343,521763,451509,325.0
30,TG,25021.0,38781.0,26738.0,121.0,1.0,183.0,NaN,1068.0,1189.0,...,2021-10-31,2021-11-01T09:54:14+05:30,37220000,671463,3956,663498,27569831,22498559,9772398,NaN
31,TN,123701.0,77325.0,106584.0,1009.0,19.0,1183.0,NaN,8827.0,7407.0,...,2021-10-31,2021-11-01T09:54:14+05:30,75695000,2702623,36116,2655015,51159242,41279432,17619141,NaN
32,TR,3501.0,3.0,650.0,12.0,NaN,2.0,NaN,49.0,87.0,...,2021-10-31,2021-11-01T09:54:14+05:30,3992000,84468,813,83466,1983127,2508477,1621329,63.0
33,TT,881379.0,750410.0,933460.0,12907.0,251.0,13152.0,1.0,109755.0,96071.0,...,2021-10-31,2021-11-01T11:20:24+05:30,1332900000,34285612,458470,33661339,609201294,732371508,330752697,13197.0
34,UP,161458.0,53401.0,57556.0,6.0,NaN,6.0,NaN,74.0,63.0,...,2021-10-31,2021-11-01T09:54:14+05:30,224979000,1710158,22900,1687151,83635222,98178865,32681895,NaN
35,UT,9524.0,1065.0,12934.0,5.0,NaN,9.0,NaN,88.0,75.0,...,2021-10-31,2021-11-01T09:54:14+05:30,11141000,343896,7400,330195,7781148,7478017,3898342,6150.0
36,WB,47417.0,209609.0,58881.0,914.0,15.0,913.0,NaN,4193.0,6453.0,...,2021-10-31,2021-11-01T09:54:14+05:30,96906000,1592908,19141,1565471,19228303,56192166,21559747,NaN

In [ ]:
# parent_table.to_csv('parent_table.csv') 
# files.download('parent_table.csv')